const packages = [
  {
    _id: "pkg_001",
    title: "Goa Beach Escape",
    location: "Goa, India",
    price: 8999,
    duration: "3 Days / 2 Nights",
    rating: 4.5,
    reviews: 124,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    description:
      "Relax on Goas stunning beaches, enjoy nightlife, and explore Portuguese heritage.",
    highlights: [
      "Beachside stay",
      "Water sports",
      "Night market visit",
      "Fort Aguada tour",
    ],
    category: "Beach",
  },
  {
    _id: "pkg_002",
    title: "Manali Snow Adventure",
    location: "Manali, Himachal Pradesh",
    price: 12999,
    duration: "5 Days / 4 Nights",
    rating: 4.7,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1605540436563-5bca919ae766",
    description:
      "Experience snow, mountains, and adventure sports in the beautiful hills of Manali.",
    highlights: [
      "Solang Valley",
      "Rohtang Pass",
      "Skiing & paragliding",
      "Mall road shopping",
    ],
    category: "Adventure",
  },
  {
    _id: "pkg_003",
    title: "Kerala Backwaters Retreat",
    location: "Alleppey, Kerala",
    price: 14999,
    duration: "4 Days / 3 Nights",
    rating: 4.8,
    reviews: 180,
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9",
    description:
      "Cruise through serene backwaters and experience Kerala's natural beauty.",
    highlights: [
      "Houseboat stay",
      "Ayurvedic spa",
      "Village walk",
      "Traditional meals",
    ],
    category: "Relaxation",
  },
  {
    _id: "pkg_004",
    title: "Rajasthan Royal Tour",
    location: "Jaipur, Udaipur, Jodhpur",
    price: 18999,
    duration: "6 Days / 5 Nights",
    rating: 4.6,
    reviews: 156,
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41",
    description: "Explore royal palaces, forts, and rich culture of Rajasthan.",
    highlights: [
      "Amber Fort",
      "City Palace",
      "Desert safari",
      "Cultural shows",
    ],
    category: "Cultural",
  },
  {
    _id: "pkg_005",
    title: "Andaman Island Getaway",
    location: "Andaman & Nicobar Islands",
    price: 22999,
    duration: "5 Days / 4 Nights",
    rating: 4.9,
    reviews: 98,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    description:
      "Crystal clear waters, coral reefs, and peaceful island vibes.",
    highlights: [
      "Scuba diving",
      "Radhanagar Beach",
      "Snorkeling",
      "Island hopping",
    ],
    category: "Beach",
  },
  {
    _id: "pkg_006",
    title: "Ladakh Road Trip",
    location: "Leh-Ladakh",
    price: 25999,
    duration: "7 Days / 6 Nights",
    rating: 4.8,
    reviews: 142,
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    description:
      "Ultimate road trip through high-altitude deserts and stunning landscapes.",
    highlights: [
      "Pangong Lake",
      "Nubra Valley",
      "Bike ride",
      "Monastery visits",
    ],
    category: "Adventure",
  },
];

export default packages;
